version: "3.5"
services:
  frontend:
    container_name: react-app-fe
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - API_URL=express-app://backend:3000
    networks:
      - ytnetwork
networks:
  ytnetwork:
    external: true
